{% set name = "roms-tools" %}
{% set version = "1.4.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/roms_tools-{{ version }}.tar.gz
  sha256: 075b698a95a0a0367e7768429e6c0a0641e2f5ad6c9a0ea4e4871b3d208341fb

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.10
    - setuptools >=61.0.0
    - wheel
    - setuptools-scm >=7.0
    - check-manifest
    - pip
  run:
    - python >=3.10
    - xarray >=2022.6.0
    - numpy
    - pooch
    - matplotlib-base
    - cartopy
    - packaging
    - scipy
    - gcm_filters
    - netcdf4
    - pyyaml
    - pyamg
    - bottleneck

test:
  imports:
    - roms_tools
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/CWorthy-ocean/roms-tools
  summary: Tools for creating input files for UCLA-ROMS simulations
  license: Apache-2.0
  license_file: LICENSE
  description: |
    **ROMS-Tools** is a Python package designed for creating the input files necessary to run a ROMS simulation. The package 
    simplifies the process of generating grid, tidal forcing, surface forcing, initial conditions, and boundary forcing.
    ROMS-Tools supports the generation of biogeochemical forcing consistent with ROMS-MARBL.

extra:
  recipe-maintainers:
    - NoraLoose
